kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - exit 0
      - dotnet sonarscanner begin
        /k:"easv-devops_KLT_currency_AY7HNVWNEVvRW2O60Elc"
        /d:sonar.host.url="http://sonar.setgo.dk:9000"
        /d:sonar.token="$SONARSECRET"
        /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"



  - name: end-to-end tests
    image: testcafe/testcafe
    commands:
      - testcafe chromium:headless Test/TestCafe.js
    depends_on:
      - update database

  - name: performance tests
    image: grafana/k6
    commands:
      - k6 run Test/spike_test.js
      - k6 run Test/StressTest.js
    depends_on:
      - end-to-end tests