services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    hostname: database
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./db/DbMigrations:/flyway/sql
      - ./db/DbMigrations:/flyway/conf
    depends_on:
      - database
  
  frontend:
    image: hoeeg79/address-book-frontend:staging
    ports:
      - 8081:80
    depends_on:
      - api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  api:
    image: hoeeg79/address-book-api:staging
    environment:
      - PGPASSWORD=/run/secrets/db_password
      - seq=http://144.91.74.225:5341
    ports:
      - 5100:8080
    secrets:
      - db_password
    depends_on:
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=/run/secrets/watchtower_http_api_token
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
    secrets:
      - watchtower_http_api_token
  
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

volumes:
  rps_seq_data:

secrets:
  db_password:
    file: db_password.txt
  watchtower_http_api_token:
    file: watchtower_http_api_token.txt